vita_add_test(p12_binding ${CMAKE_CURRENT_SOURCE_DIR}/binding.cpp)
set_tests_properties(p12_binding PROPERTIES LABELS "transport;integration")
if(TARGET vita::posix_udp)
  vita_add_test(p12_socket ${CMAKE_CURRENT_SOURCE_DIR}/socket.cpp)
  target_link_libraries(p12_socket PRIVATE vita::posix_udp)
  set_tests_properties(p12_socket PROPERTIES LABELS "udp;transport")
  vita_add_test(p12_adapter ${CMAKE_CURRENT_SOURCE_DIR}/adapter.cpp)
  target_link_libraries(p12_adapter PRIVATE vita::posix_udp)
  set_tests_properties(p12_adapter PROPERTIES LABELS "udp;transport;integration")
  vita_add_test(p12_runtime_binding ${CMAKE_CURRENT_SOURCE_DIR}/runtime_binding.cpp)
  target_link_libraries(p12_runtime_binding PRIVATE vita::posix_udp)
  set_tests_properties(p12_runtime_binding PROPERTIES LABELS "udp;transport;integration")
endif()
