#include <vita/codec/packet.hpp>
#include <algorithm>
#include <cassert>
#include <cstdlib>
#include <new>
using namespace vita;using namespace vita::codec;
static std::size_t allocs=0;
void* operator new(std::size_t n){++allocs;if(auto p=std::malloc(n?n:1))return p;std::abort();}void* operator new[](std::size_t n){return ::operator new(n);}void* operator new(std::size_t n,std::align_val_t a){++allocs;void*p=nullptr;if(!posix_memalign(&p,std::size_t(a),n?n:1))return p;std::abort();}void* operator new[](std::size_t n,std::align_val_t a){return ::operator new(n,a);}void operator delete(void*p)noexcept{std::free(p);}void operator delete[](void*p)noexcept{std::free(p);}void operator delete(void*p,std::align_val_t)noexcept{std::free(p);}void operator delete[](void*p,std::align_val_t)noexcept{std::free(p);}
template<std::size_t N>static auto bytes(const std::array<std::uint32_t,N>&words){std::array<std::byte,N*4>b{};for(std::size_t i=0;i<N;++i)for(unsigned j=0;j<4;++j)b[4*i+j]=std::byte((words[i]>>(24-8*j))&255);return b;}
static auto frozen(){NativeContextPacket<64> b;UuidValue u{{0x00112233,0x44556677,0x8899aabb,0xccddeeff}};assert(b.set<ControlleeUUID>(u));u.words[0]=0xfedcba98;assert(b.set<ControllerUUID>(u));auto copy=b.freeze();u.words.fill(0);u.words[3]=1;assert(b.replace<ControlleeUUID>(u));return copy;}
int main(){static_assert(sizeof(SemanticValue)==16);Envelope e;e.type=PacketType::context;e.stream_id=1;
 const auto literal=bytes(std::array<std::uint32_t,12>{0x4000000c,1,4,0x01400000,0x00112233,0x44556677,0x8899aabb,0xccddeeff,0xfedcba98,0x44556677,0x8899aabb,0xccddeeff});
 auto snap=frozen();assert(snap.get<ControlleeUUID>()->words[0]==0x00112233);auto clone=snap;assert(clone.get<ControllerUUID>()->words[3]==0xccddeeff);std::array<std::byte,64> out{};auto n=encode_packet(e,clone,out);assert(n&&*n==literal.size()&&std::equal(literal.begin(),literal.end(),out.begin()));
 auto parse=decode_packet(literal);assert(parse&&parse->fields.size()==2);assert(parse->fields[0].uuid()->words[0]==0x00112233);assert(parse->fields[1].uuid()->words[0]==0xfedcba98);NativeContextPacket<32> restored;for(std::size_t i=0;i<2;++i)assert(parse->fields[i].materialize_into(restored));auto rs=restored.freeze();assert(rs.get<ControlleeUUID>()==snap.get<ControlleeUUID>());assert(rs.get<ControllerUUID>()==snap.get<ControllerUUID>());
 for(std::size_t cut=0;cut<literal.size();++cut){unsigned callbacks=0;auto r=decode_and_visit(Bytes{literal}.first(cut),{},[&](FieldView)noexcept->Result<void>{++callbacks;return {};});assert(!r&&callbacks==0);}
 NativeContextPacket<16> small;UuidValue a{{1,2,3,4}},b{{5,6,7,8}};assert(small.set<ControlleeUUID>(a));auto old=small.freeze();assert(!small.set<ControllerUUID>(b));assert(small.freeze().generation()==old.generation());for(unsigned k=0;k<100;++k){assert(small.replace<ControlleeUUID>(b));assert(small.freeze().native_size()==16);}assert(old.get<ControlleeUUID>()->words==a.words);assert(small.remove<ControlleeUUID>());assert(small.set<ControllerUUID>(a));ContextPacket noarena;assert(!noarena.set<ControlleeUUID>(a));
 // Zero UUID is structurally recoverable but is not a valid assigned identifier.
 const auto zero_wire=bytes(std::array<std::uint32_t,8>{0x40000008,1,4,0x01000000,0,0,0,0});auto zero=decode_packet(zero_wire);assert(zero&&zero->fields[0].uuid()&&zero->fields[0].uuid()->words==UuidValue{}.words);auto stable=small.freeze();assert(!small.replace<ControllerUUID>(UuidValue{}));NativeContextPacket<32> empty;assert(!zero->fields[0].materialize_into(empty));assert(empty.freeze().native_size()==0&&empty.freeze().fields().empty());auto after=small.freeze();assert(after.generation()==stable.generation()&&after.get<ControllerUUID>()==stable.get<ControllerUUID>());
 // UUID data changes are not layout changes; refs from a different owner cannot be injected.
 NativeContextPacket<32> other;assert(other.set<ControlleeUUID>(b));assert(other.set<ControllerUUID>(a));auto os=other.freeze();auto measured=measure(snap);assert(measured&&validate_measure(os,*measured));const auto&foreign=*snap.fields()[0].values[0];assert(!other.set_value(ControlleeUUID::id,foreign));
 const auto before=allocs;for(unsigned iteration=0;iteration<1000;++iteration){auto s=frozen();auto c=s;auto encoded=encode_packet(e,c,out);assert(encoded);auto p=decode_packet(Bytes{out}.first(*encoded));assert(p);NativeContextPacket<32> target;for(std::size_t i=0;i<p->fields.size();++i)assert(p->fields[i].materialize_into(target));auto materialized=target.freeze();assert(materialized.get<ControlleeUUID>()==s.get<ControlleeUUID>());}assert(allocs==before);auto*p=::operator new(32);auto*q=::operator new(32,std::align_val_t{32});assert(allocs==before+2);::operator delete(p);::operator delete(q,std::align_val_t{32});
}
