#include <vita/codec/packet.hpp>
#include <cassert>
#include <vector>
#include <algorithm>
using namespace vita;using namespace vita::codec;
static void word(std::vector<std::byte>&b,std::uint32_t w){for(int i=3;i>=0;--i)b.push_back(std::byte((w>>(i*8))&255));}
static std::vector<std::byte> packet(unsigned tsi,unsigned tsf){const unsigned t=(tsi?1:0)+(tsf?2:0);std::vector<std::byte>b;word(b,0x40000000|(tsi<<22)|(tsf<<20)|(4+3*t));word(b,1);if(tsi)word(b,99);if(tsf){word(b,0);word(b,17);}word(b,8);word(b,0x00030000);for(unsigned f=0;f<2;++f){if(tsi)word(b,0xabcdef00+f);if(tsf){word(b,0xfedcba98);word(b,0x76543210+f);}}return b;}
int main(){for(unsigned tsi=0;tsi<4;++tsi)for(unsigned tsf=0;tsf<4;++tsf){auto raw=packet(tsi,tsf);auto p=decode_packet(raw);if(!tsi&&!tsf){assert(!p);continue;}assert(p&&p->fields.size()==2);const auto t=(tsi?1:0)+(tsf?2:0);for(unsigned i=0;i<2;++i){assert(p->fields[i].id==(FieldId{3,static_cast<std::uint8_t>(17-i)}));assert(p->fields[i].bytes.size()==t*4);auto value=p->fields[i].duration();assert(value&&value->tsi==tsi&&value->tsf==tsf&&value->seconds==(tsi?0xabcdef00u+i:0)&&value->fractional==(tsf?0xfedcba9876543210ull+i:0));auto forged=p->fields[i];for(std::size_t n=0;n<forged.bytes.size();++n){auto short_view=forged;short_view.bytes=forged.bytes.first(n);assert(!short_view.duration());}forged.timestamp_format.tsi=4;assert(!forged.duration());}
 NativeContextPacket<64> builder;assert(builder.bind_timestamp_format(tsi,tsf));for(unsigned i=0;i<2;++i)assert(p->fields[i].materialize_into(builder));auto snapshot=builder.freeze();auto m=measure(snapshot);auto idx=index_layout<4>(snapshot);assert(m&&idx&&idx->size()==2&&(*idx)[0].offset==8&&(*idx)[0].bytes==4*t&&(*idx)[1].offset==8+4*t&&(*idx)[1].bytes==4*t);Envelope env;env.type=PacketType::context;env.stream_id=1;env.timestamp={static_cast<Tsi>(tsi),static_cast<Tsf>(tsf),99,17};std::array<std::byte,64> output{};auto encoded=encode_packet(env,snapshot,output);assert(encoded&&*encoded==raw.size()&&std::equal(raw.begin(),raw.end(),output.begin()));
 for(std::size_t length=0;length<raw.size();++length){unsigned calls=0;auto r=decode_and_visit(Bytes{raw}.first(length),{},[&](FieldView)noexcept->Result<void>{++calls;return {};});assert(!r&&calls==0);}output.fill(std::byte{0x55});env.timestamp.tsf=static_cast<Tsf>((tsf+1)%4);assert(!encode_packet(env,snapshot,output));assert(std::all_of(output.begin(),output.end(),[](auto b){return b==std::byte{0x55};}));
 env.timestamp.tsf=static_cast<Tsf>(tsf);env.timestamp.tsi=static_cast<Tsi>((tsi+1)%4);assert(!encode_packet(env,snapshot,output));assert(std::all_of(output.begin(),output.end(),[](auto b){return b==std::byte{0x55};}));
 // Binding must never reinterpret an already inserted code, even at identical extent.
 const auto old_generation=builder.freeze().generation();assert(!builder.bind_timestamp_format(tsi,(tsf+1)%4));assert(builder.freeze().generation()==old_generation);assert(builder.remove<Age>()&&builder.remove<ShelfLife>());assert(builder.bind_timestamp_format(tsi,(tsf+1)%4));assert(snapshot.get<Age>()->tsf==tsf);
 }
 NativeContextPacket<64> a,b;assert(a.bind_timestamp_format(1,1));assert(b.bind_timestamp_format(1,2));assert(a.set<Age>(StateDurationValue{7,9,1,1}));assert(b.set<Age>(StateDurationValue{7,9,1,2}));auto sa=a.freeze(),sb=b.freeze();auto ma=measure(sa),mb=measure(sb);assert(ma&&mb&&ma->bytes==mb->bytes&&sa.generation()==sb.generation());assert(!validate_measure(sb,*ma));NativeContextPacket<64> c;assert(c.bind_timestamp_format(2,1));assert(c.set<Age>(StateDurationValue{7,9,2,1}));auto sc=c.freeze();auto mc=measure(sc);assert(mc&&mc->bytes==ma->bytes&&sc.generation()==sa.generation()&&!validate_measure(sc,*ma));
 NativeContextPacket<64> unbound;assert(unbound.set<Age>(StateDurationValue{7,9,1,1}));assert(!measure(unbound.freeze()));assert(!unbound.bind_timestamp_format(0,0));assert(unbound.remove<Age>());assert(unbound.bind_timestamp_format(0,0));assert(!unbound.set<Age>(StateDurationValue{}));
}
