#include <vita/codec/packet.hpp>
#include <cassert>
#include <algorithm>
#include <cstdlib>
#include <new>
using namespace vita;using namespace vita::codec;
static std::size_t allocs=0;
void* operator new(std::size_t n){++allocs;if(auto p=std::malloc(n?n:1))return p;std::abort();}void* operator new[](std::size_t n){return ::operator new(n);}void* operator new(std::size_t n,std::align_val_t a){++allocs;void*p=nullptr;if(!posix_memalign(&p,std::size_t(a),n?n:1))return p;std::abort();}void* operator new[](std::size_t n,std::align_val_t a){return ::operator new(n,a);}void operator delete(void*p)noexcept{std::free(p);}void operator delete[](void*p)noexcept{std::free(p);}void operator delete(void*p,std::align_val_t)noexcept{std::free(p);}void operator delete[](void*p,std::align_val_t)noexcept{std::free(p);}

static Result<void> sentence(void*,std::span<const char>)noexcept{return {};}
static AttributeInput scalar(FieldId f,Attribute a,SemanticValue v){return {f,a,InputValue{v}};}
int main(){constexpr auto current=Attribute::current,minimum=Attribute::minimum,probability=Attribute::probability;const auto mask=attribute_bit(current)|attribute_bit(minimum)|attribute_bit(probability);char first[]{'A','B','C','D'},second[]{'E','F','G','H','I','J','K','L'};
 NativeContextPacket<256> b;assert(b.set<GPSASCII>(GpsAsciiInput{1,first,{nullptr,sentence}}));assert(b.set<SampleRate>(Hertz{1}));auto initial=b.freeze();std::array<AttributeInput,4> inputs{{{GPSASCII::id,minimum,InputValue{GpsAsciiInput{2,second,{nullptr,sentence}}}},scalar(GPSASCII::id,probability,ProbabilityCode{128,255}),scalar(SampleRate::id,minimum,Hertz{2}),scalar(SampleRate::id,probability,ProbabilityCode{255,0})}};EditWorkspace<BodyKind::values,16,256> workspace;assert(b.with_attribute_inputs(mask,inputs,workspace));auto old=b.freeze();assert(old.generation()==initial.generation()+1);assert(old.get<GPSASCII>()->text.size()==4&&old.get<GPSASCII>(minimum)->text.size()==8&&old.probability(GPSASCII::id)==(ProbabilityCode{128,255}));
 Envelope env;env.type=PacketType::context;env.stream_id=1;std::array<std::byte,256> before{},after{};auto n=encode_packet(env,old,before);assert(n);auto borrowed=old.get<GPSASCII>(minimum);assert(borrowed);assert(b.replace_attribute<GPSASCII>(current,GpsAsciiInput{3,borrowed->text,{nullptr,sentence}}));auto now=b.freeze();assert(now.generation()==old.generation()+1&&now.get<GPSASCII>()->text.size()==8&&now.get<GPSASCII>(minimum)->oui==2&&now.probability(GPSASCII::id)==old.probability(GPSASCII::id));assert(encode_packet(env,old,after)&&before==after);assert(initial.get<GPSASCII>()->text.size()==4);
 auto materialization_target=b;auto original_wire=decode_packet(Bytes{before}.first(*n));assert(original_wire);bool materialized=false;for(std::size_t i=0;i<original_wire->fields.size();++i){auto&field=original_wire->fields[i];if(field.id==GPSASCII::id&&field.attribute==minimum){assert(field.materialize_into(materialization_target,{nullptr,sentence}));materialized=true;}}auto materialized_snapshot=materialization_target.freeze();assert(materialized&&materialized_snapshot.get<GPSASCII>()->oui==3&&materialized_snapshot.get<GPSASCII>(minimum)->oui==2);
 auto stable=b.freeze();std::array<AttributeInput,2> duplicate{inputs[0],inputs[0]};assert(!b.with_attribute_inputs(mask,duplicate,workspace));assert(b.freeze().generation()==stable.generation());std::array<char,1024> large{};large.fill('Q');assert(!b.replace_attribute<GPSASCII>(minimum,GpsAsciiInput{5,large,{nullptr,sentence}}));assert(b.freeze().generation()==stable.generation());assert(!b.with_attributes(mask|attribute_bit(Attribute::belief)));assert(b.freeze().generation()==stable.generation());
 // Cross-owner native slice cannot be inserted even when its bounds happen to fit.
 const auto& raw=*old.fields()[0].values[0];if(std::holds_alternative<NativeSlice>(raw)){std::array<AttributeInput,1> forged{scalar(old.fields()[0].id,current,raw)};assert(!b.with_attribute_inputs(mask,forged));}else{const auto& own=*old.fields()[1].values[0];assert(std::holds_alternative<NativeSlice>(own));std::array<AttributeInput,1> forged{scalar(old.fields()[1].id,current,own)};assert(!b.with_attribute_inputs(mask,forged));}
 UuidValue uuid{{1,2,3,4}};std::array<AttributeInput,1> incomplete{{{ControlleeUUID::id,current,InputValue{uuid}}}};assert(!b.set_field_attributes<ControlleeUUID>(incomplete));assert(b.freeze().generation()==stable.generation());std::array<AttributeInput,3> complete{{{ControlleeUUID::id,current,InputValue{uuid}},{ControlleeUUID::id,minimum,InputValue{UuidValue{{5,6,7,8}}}},scalar(ControlleeUUID::id,probability,ProbabilityCode{1,2})}};assert(b.set_field_attributes<ControlleeUUID>(complete,workspace));auto with_uuid=b.freeze();assert(with_uuid.get<ControlleeUUID>()->words[0]==1&&with_uuid.get<ControlleeUUID>(minimum)->words[0]==5);
 // Probability-only structured fields need no native arena or timestamp binding.
 ContextPacket codes;assert(codes.with_attributes(attribute_bit(probability)|attribute_bit(Attribute::belief)));for(auto id:{GPSASCII::id,Age::id,ControlleeUUID::id}){std::array<AttributeInput,2> entry{scalar(id,probability,ProbabilityCode{7,8}),scalar(id,Attribute::belief,BeliefCode{9})};if(id==GPSASCII::id)assert(codes.set_field_attributes<GPSASCII>(entry));else if(id==Age::id)assert(codes.set_field_attributes<Age>(entry));else assert(codes.set_field_attributes<ControlleeUUID>(entry));}assert(measure(codes.freeze()));std::array<std::byte,64> wire{};auto count=encode_packet(env,codes.freeze(),wire);assert(count);auto parsed=decode_packet(Bytes{wire}.first(*count));assert(parsed&&parsed->fields.size()==6);assert(codes.set_probability(Age::id,{255,255}));assert(codes.set_belief(GPSASCII::id,{128}));
 // NonCurrent representability is not Current physical validity.
 NativeContextPacket<128> derivatives;assert(derivatives.with_attributes(attribute_bit(Attribute::first_derivative)));GeolocationValue g;g.latitude_q22=91*(1<<22);std::array<AttributeInput,1> derivative{{{FormattedGPS::id,Attribute::first_derivative,InputValue{g}}}};assert(derivatives.set_field_attributes<FormattedGPS>(derivative));assert(measure(derivatives.freeze()));ContextPacket rates;assert(rates.with_attributes(attribute_bit(Attribute::first_derivative)));std::array<AttributeInput,1> negative{scalar(SampleRate::id,Attribute::first_derivative,Hertz{-1})};assert(rates.set_field_attributes<SampleRate>(negative));assert(measure(rates.freeze()));
assert(allocs==0);auto*p=::operator new(32);auto*q=::operator new(64,std::align_val_t{64});assert(allocs==2);::operator delete(p);::operator delete(q,std::align_val_t{64});
}
