#include <vita/codec/extensions.hpp>
#include <cassert>
#include <array>
#include <algorithm>
#include <cstdlib>
#include <new>
using namespace vita;using namespace vita::codec;using namespace vita::codec::extensions;
static std::size_t allocs=0;
void* operator new(std::size_t n){++allocs;if(auto p=std::malloc(n?n:1))return p;std::abort();}void* operator new[](std::size_t n){return ::operator new(n);}void* operator new(std::size_t n,std::align_val_t a){++allocs;void*p=nullptr;if(!posix_memalign(&p,std::size_t(a),n?n:1))return p;std::abort();}void* operator new[](std::size_t n,std::align_val_t a){return ::operator new(n,a);}void operator delete(void*p)noexcept{std::free(p);}void operator delete[](void*p)noexcept{std::free(p);}void operator delete(void*p,std::align_val_t)noexcept{std::free(p);}void operator delete[](void*p,std::align_val_t)noexcept{std::free(p);}

struct Counts{unsigned parsed=0,admitted=0,executed=0;bool allow=false;};
static Result<void> parse(void*p,const EnvelopeView&v,WorkBudget&w)noexcept{++static_cast<Counts*>(p)->parsed;auto charge=w.consume(2);if(!charge)return charge;if(v.payload.size()!=4||v.payload[0]!=std::byte{0xde})return std::unexpected(Error{ErrorCode::invalid_argument});return {};}
static Result<void> admit(void*p,ClassKey,const EnvelopeView&)noexcept{auto&c=*static_cast<Counts*>(p);++c.admitted;if(!c.allow)return std::unexpected(Error{ErrorCode::capacity_exhausted});return {};}
static Result<void> execute(void*p,const EnvelopeView&)noexcept{++static_cast<Counts*>(p)->executed;return {};}
static Result<std::size_t> size(void*,const void*,WorkBudget&)noexcept{return 4;}
static Result<void> encode(void*,const void*,MutableBytes bytes,WorkBudget&)noexcept{bytes[0]=std::byte{0xde};bytes[1]=std::byte{0xad};bytes[2]=std::byte{0xbe};bytes[3]=std::byte{0xef};return {};}
static Result<void> fullwire(void*,const EnvelopeView&view,WorkBudget&)noexcept{auto decoded=decode_envelope(view.wire);if(!decoded||decoded->payload_offset!=view.payload_offset||decoded->payload.data()!=view.payload.data()||decoded->envelope.stream_id!=view.envelope.stream_id)return std::unexpected(Error{ErrorCode::invalid_argument});return {};}
static auto literal(){std::array<std::uint32_t,5>w{0x58000005,0x12345678,0x00ff0001,0x43211234,0xdeadbeef};std::array<std::byte,20>b{};for(unsigned i=0;i<5;++i)for(unsigned j=0;j<4;++j)b[4*i+j]=std::byte((w[i]>>(24-j*8))&255);return b;}
static void families();
int main(){families();Counts c;Descriptor d;d.key={PacketType::extension_context,0xff0001,0x4321,0x1234};d.context=&c;d.min_payload=d.max_payload=4;d.validate=parse;d.dispatch=execute;Registry<1> r;assert(r.add(d));assert(!r.add(d));auto wire=literal();WorkBudget before;assert(!r.validate(wire,before));r.freeze();assert(!r.add(d));WorkBudget work(4);auto v=r.validate(wire,work);assert(v&&!v->opaque()&&work.remaining()==0&&c.parsed==1&&c.admitted==0&&c.executed==0);assert(v->envelope().envelope.stream_id==0x12345678);assert(!r.dispatch(*v,{}));assert(!r.dispatch(*v,{&c,admit}));assert(c.admitted==1&&c.executed==0);c.allow=true;assert(r.dispatch(*v,{&c,admit}));assert(r.dispatch(*v,{&c,admit}));assert(c.admitted==3&&c.executed==2);
 Registry<1> other;assert(other.add(d));other.freeze();assert(!other.dispatch(*v,{&c,admit}));assert(c.admitted==3);
 for(unsigned n=0;n<wire.size();++n){WorkBudget w;auto p=r.validate(Bytes{wire}.first(n),w);assert(!p&&c.parsed==1);}
 auto unknown=wire;unknown[15]=std::byte{0x35};WorkBudget uw;auto opaque=r.validate(unknown,uw);assert(opaque&&opaque->opaque()&&c.parsed==1);assert(!r.dispatch(*opaque,{&c,admit}));
 auto malformed=wire;malformed[16]=std::byte{0};WorkBudget mw;assert(!r.validate(malformed,mw));assert(c.parsed==2&&c.admitted==3&&c.executed==2);
 WorkBudget exhausted(1);assert(!r.validate(wire,exhausted));assert(c.parsed==2&&exhausted.remaining()==1);WorkBudget callbacklimited(3);assert(!r.validate(wire,callbacklimited));assert(c.parsed==3&&callbacklimited.remaining()==1);
 Registry<1> consistent;auto full=d;full.validate=fullwire;full.measure=size;full.encode=encode;assert(consistent.add(full));consistent.freeze();Envelope env;env.type=PacketType::extension_context;env.stream_id=0x12345678;env.class_id=ClassId{0xff0001,0x4321,0x1234,0};std::array<std::byte,20> output{};WorkBudget encoding;auto encoded=consistent.encode(env,nullptr,{},output,encoding);assert(encoded&&*encoded==wire.size()&&output==wire);WorkBudget checking;assert(consistent.validate(output,checking));
}
struct Wire {std::array<std::byte,64> bytes{};std::size_t size=0;Bytes view()const noexcept{return Bytes{bytes}.first(size);}void word(std::uint32_t value){for(int i=3;i>=0;--i)bytes[size++]=std::byte((value>>(i*8))&255);}};
static Wire oracle(unsigned family,bool ack=false,bool trailer=false){Wire w;const unsigned count=4+(family!=2)+(family==7?2:0)+(trailer?1:0);w.word((family<<28)|0x08000000|(ack?0x04000000:0)|(trailer?0x04000000:0)|count);if(family!=2)w.word(0x12345678);w.word(0x00ff0001);w.word(0x43211234);if(family==7){w.word(ack?0x01080080:0x01000002);w.word(0x87654321);}w.word(0xdeadbeef);if(trailer)w.word(0x81234567);return w;}
struct Probe {unsigned validation=0,admission=0,execution=0,encoding=0;bool denied=false,encode_failure=false,validation_failure=false;};
static Result<void> checked(void*raw,const EnvelopeView&v,WorkBudget&w)noexcept{auto&p=*static_cast<Probe*>(raw);++p.validation;auto charge=w.consume();if(!charge)return charge;auto parsed=decode_envelope(v.wire);if(!parsed||parsed->payload.data()!=v.payload.data()||parsed->payload_offset!=v.payload_offset||parsed->trailer!=v.trailer||v.payload.size()!=4||v.payload[0]!=std::byte{0xde}||v.payload[3]!=std::byte{0xef}||p.validation_failure)return std::unexpected(Error{ErrorCode::invalid_argument});return {};}
static Result<void> authorized(void*raw,ClassKey,const EnvelopeView&)noexcept{auto&p=*static_cast<Probe*>(raw);++p.admission;if(p.denied)return std::unexpected(Error{ErrorCode::capacity_exhausted});return {};}
static Result<void> invoked(void*raw,const EnvelopeView&)noexcept{++static_cast<Probe*>(raw)->execution;return {};}
static Result<void> encoded(void*raw,const void*,MutableBytes out,WorkBudget&)noexcept{auto&p=*static_cast<Probe*>(raw);++p.encoding;out[0]=std::byte{0xde};if(p.encode_failure)return std::unexpected(Error{ErrorCode::callback_failure});out[1]=std::byte{0xad};out[2]=std::byte{0xbe};out[3]=std::byte{0xef};return {};}
static void families(){auto allocations_before=allocs;
for(unsigned family:{2u,3u,5u,7u})for(bool acknowledgement:{false,true}){if(acknowledgement&&family!=7)continue;Probe p;Descriptor d;d.key={static_cast<PacketType>(family),0xff0001,0x4321,0x1234};d.context=&p;d.validate=checked;d.measure=size;d.encode=encoded;d.dispatch=invoked;d.min_payload=d.max_payload=4;if(family==7){d.header.allowed_flags=ack_flag;d.control_cam_extensions=2;d.ack_cam_extensions=128;}else if(family<4)d.header.allowed_flags=trailer_flag;Registry<1> r;assert(r.add(d));r.freeze();auto raw=oracle(family,acknowledgement);WorkBudget work;auto v=r.validate(raw.view(),work);assert(v&&!v->opaque()&&p.validation==1&&!p.execution&&!p.admission);auto env=v->envelope().envelope;assert(env.stream_id.has_value()==(family!=2));if(family==7){assert(env.command->message_id==0x87654321);assert(env.ack==acknowledgement);}
 // The same validator sees a complete coherent envelope on encoding and receive.
 std::array<std::byte,64> out{};auto n=r.encode(env,nullptr,{},out,work);assert(n&&*n==raw.size&&std::equal(raw.view().begin(),raw.view().end(),out.begin()));assert(p.validation==2&&p.encoding==1&&!p.execution&&!p.admission);
 for(std::size_t cut=0;cut<raw.size;++cut){WorkBudget b;assert(!r.validate(raw.view().first(cut),b));assert(p.validation==2);}
 p.denied=true;assert(!r.dispatch(*v,{&p,authorized}));assert(p.admission==1&&!p.execution);p.denied=false;assert(r.dispatch(*v,{&p,authorized}));assert(p.admission==2&&p.execution==1);
 // Every identity component is exact; unknown classes never invoke callbacks.
 for(std::size_t byte:{std::size_t(family==2?5:9),std::size_t(family==2?8:12),std::size_t(family==2?11:15)}){auto unknown=raw;unknown.bytes[byte]^=std::byte{1};WorkBudget b;auto opaque=r.validate(unknown.view(),b);assert(opaque&&opaque->opaque()&&p.validation==2);assert(!r.dispatch(*opaque,{&p,authorized}));}
 for(unsigned other:{2u,3u,5u,7u})if(other!=family){auto different=oracle(other);WorkBudget b;auto opaque=r.validate(different.view(),b);assert(opaque&&opaque->opaque()&&p.validation==2);}
 auto classless=env;classless.class_id.reset();auto unclassified=encode_envelope(classless,v->envelope().payload,{},out);assert(unclassified);WorkBudget unclassified_budget;auto opaque=r.validate(Bytes{out}.first(*unclassified),unclassified_budget);assert(opaque&&opaque->opaque()&&p.validation==2);assert(!r.dispatch(*opaque,{&p,authorized}));
 // Short output, insufficient framework budget and forbidden flags fail before encoder.
 out.fill(std::byte{0xa5});const auto before=p.encoding;assert(!r.encode(env,nullptr,{},MutableBytes{out}.first(raw.size-1),work));assert(p.encoding==before&&std::all_of(out.begin(),out.end(),[](auto b){return b==std::byte{0xa5};}));WorkBudget none(0);assert(!r.encode(env,nullptr,{},out,none));assert(p.encoding==before);auto timed=env;timed.timestamp.tsi=Tsi::gps;assert(!r.encode(timed,nullptr,{},out,work));assert(p.encoding==before);
 // Registered callback failures may alter output, but can never dispatch.
 p.encode_failure=true;assert(!r.encode(env,nullptr,{},out,work));assert(out[raw.size-4]==std::byte{0xde}&&p.execution==1);p.encode_failure=false;p.validation_failure=true;assert(!r.encode(env,nullptr,{},out,work));assert(p.execution==1);p.validation_failure=false;
 if(family==7){const auto callbacks=p.validation;auto bit0=raw;bit0.bytes[19]|=std::byte{1};assert(!decode_envelope(bit0.view()));WorkBudget b;assert(!r.validate(bit0.view(),b));auto e=env;e.command->cam|=1;out.fill(std::byte{0xa5});assert(!encode_envelope(e,v->envelope().payload,{},out));assert(!r.encode(e,nullptr,{},out,b));assert(p.validation==callbacks);for(unsigned bit=1;bit<8;++bit){auto custom=raw;custom.bytes[19]=std::byte(1u<<bit);WorkBudget budget;auto permitted=r.validate(custom.view(),budget);assert(bool(permitted)==(acknowledgement?bit==7:bit==1));}}
 if(family<4){auto with_trailer=oracle(family,false,true);WorkBudget b;auto data=r.validate(with_trailer.view(),b);assert(data&&data->envelope().trailer==0x81234567);auto n2=r.encode(data->envelope().envelope,nullptr,0x81234567,out,b);assert(n2&&*n2==with_trailer.size&&std::equal(with_trailer.view().begin(),with_trailer.view().end(),out.begin()));}
}
assert(allocs==allocations_before);auto*p=::operator new(32);auto*q=::operator new(64,std::align_val_t{64});assert(allocs==allocations_before+2);::operator delete(p);::operator delete(q,std::align_val_t{64});
}
