#include <vita/codec/numeric_samples.hpp>
#include <cassert>
#include <cstdlib>
#include <new>
#include <type_traits>
using namespace vita::codec::numeric;
static unsigned allocations=0;
void* operator new(std::size_t n){++allocations;if(auto p=std::malloc(n?n:1))return p;std::abort();}void* operator new[](std::size_t n){return ::operator new(n);}void* operator new(std::size_t n,std::align_val_t a){++allocations;void*p=nullptr;if(!posix_memalign(&p,std::size_t(a),n?n:1))return p;std::abort();}void* operator new[](std::size_t n,std::align_val_t a){return ::operator new(n,a);}void operator delete(void*p)noexcept{std::free(p);}void operator delete[](void*p)noexcept{std::free(p);}void operator delete(void*p,std::align_val_t)noexcept{std::free(p);}void operator delete[](void*p,std::align_val_t)noexcept{std::free(p);}
int main(){static_assert(!std::is_default_constructible_v<ConversionPolicy>);static_assert(sizeof(BinaryValue)==16);const ConversionPolicy exact{Precision::exact_only,Rounding::nearest_ties_even,Overflow::error,VrtEncoding::lowest_exponent};const ConversionPolicy lossy{Precision::allow_rounding,Rounding::nearest_ties_even,Overflow::saturate,VrtEncoding::lowest_exponent};
 NumericSpec u{Kind::unsigned_vrt,5,0,2},s{Kind::signed_vrt,5,0,2};assert((decode_exact(u,31)==BinaryValue{7,-3,false}));assert((decode_exact(u,4)==BinaryValue{1,-6,false}));assert((decode_exact(u,16)==BinaryValue{1,-4,false}));assert((decode_exact(s,31)==BinaryValue{1,-2,true}));assert((decode_exact(s,28)==BinaryValue{1,-5,true}));assert((decode_exact(s,19)==BinaryValue{1,0,true}));assert((decode_exact(s,15)==BinaryValue{3,-2,false}));
 for(auto spec:{NumericSpec{Kind::unsigned_fixed,0},NumericSpec{Kind::signed_fixed,65},NumericSpec{Kind::unsigned_fixed,8,1},NumericSpec{Kind::signed_non_normalized,8,8},NumericSpec{Kind::signed_non_normalized,64,16},NumericSpec{Kind::signed_vrt,8,1,2},NumericSpec{Kind::unsigned_vrt,6,0,6},NumericSpec{Kind::unsigned_vrt,64,0,7},NumericSpec{static_cast<Kind>(99),8}}){assert(!decode_exact(spec,0));assert(!encode_numeric(spec,{0,0,false},exact));}
 assert(!decode_exact(u,32));assert(!encode_numeric(u,{1,0,false},{Precision::exact_only,Rounding::nearest_ties_even,Overflow::saturate,VrtEncoding::lowest_exponent}));auto zero=encode_numeric(s,{0,32767,true},exact);assert(zero&&zero->bits==0&&!zero->rounded&&!zero->saturated);auto policy=exact;policy.rounding=static_cast<Rounding>(99);assert(!encode_numeric(s,{1,-2,false},policy));
 auto before=allocations;for(unsigned n=1;n<=64;++n)for(unsigned i=0;i<100;++i){NumericSpec source{Kind::signed_fixed,n};std::uint64_t raw=n==64?UINT64_MAX:(std::uint64_t{1}<<n)-1;auto v=decode_exact(source,raw);assert(v);auto encoded=encode_numeric(source,*v,exact);assert(encoded&&encoded->bits==raw);auto converted=convert_numeric(source,raw,NumericSpec{Kind::unsigned_vrt,64,0,6},lossy);assert(converted&&converted->bits==0&&converted->saturated);}assert(allocations==before);auto*p=::operator new(32);auto*q=::operator new(64,std::align_val_t{64});assert(allocations==before+2);::operator delete(p);::operator delete(q,std::align_val_t{64});
}
