#include <vita/profiles/iq/lab.hpp>
#include <vita/runtime/public/runtime.hpp>
#include <cassert>
#include <cstdio>
using namespace vita;
struct Received {unsigned count=0;std::int64_t rf=0;static void deliver(void* p,const runtime::context::BorrowedSignalRx& rx)noexcept {auto& self=*static_cast<Received*>(p);assert(rx.metadata.confidence==runtime::context::Confidence::known);++self.count;self.rf=std::get<Hertz>(rx.metadata.state.fields[4].value).q20;}};
static void trial(bool future,std::size_t mtu=100,bool late_start=false,bool jump_from_below=false,bool refresh_before=false){
 auto config=profiles::iq::lab::config(0xabcdef);auto pools=profiles::iq::lab::pools();assert(config&&pools);if(refresh_before)config->clock.holdover_limit_ns=5'000'000'000;auto made=VitaRuntime<2,4,32,65536>::create(*config,std::move(*pools));assert(made);auto& runtime=**made;
 auto backend=std::make_shared<runtime::transaction::VirtualBackend<4>>();StreamConfig source;source.sid=1;source.controller_id=2;source.controllee_id=3;source.sample_rate=100000;source.profile=profiles::iq::Profile::frequency_tunable;Received received;source.ip_mtu=mtu;source.receiver={&received,Received::deliver,nullptr};source.device={backend->binding(),backend,sizeof(*backend),nullptr};auto device=runtime.add_controllee(source);assert(device);auto controller=runtime.add_controller(*device);assert(controller);assert(runtime.observe_pps({0},{1000,0})&&device->start());if(future){assert(runtime.progress({0}));assert(received.count==1);}
 CommandOptions options;if(future){options.timing_mode=1;options.execute_at=refresh_before?runtime::timing::ProtocolTime{1003,30'000'000}:runtime::timing::ProtocolTime{1000,1'100'000'000};}
 auto tune=controller->set_center_frequency(*Hertz::from_integer(100025000),options);assert(tune);
 assert(runtime.progress({late_start?1000u:0u}));if(late_start){assert(received.count<=1);if(received.count)assert(received.rf==100000000ll*(1ll<<20));assert(runtime.progress({2'560'000}));}
 if(future){assert(runtime.progress({550'000}));assert(received.count>1);assert(received.rf==100000000ll*(1ll<<20));if(!jump_from_below&&!refresh_before)assert(runtime.progress({1'100'000}));}
 const auto before=received.count;const std::uint64_t hold=refresh_before?1'500'000'000:future?1'002'500'000:late_start?3'500'000:2'500'000;assert(runtime.progress({hold}));if(jump_from_below||refresh_before){assert(backend->pending()==0&&backend->writes()==0);assert(device->confirmed_state().fields[4].value==SemanticValue{*Hertz::from_integer(100000000)});auto evidence=controller->wait(*tune,0);assert(evidence&&!evidence->observation.confirms_execution);assert(runtime.progress({hold+100'000}));if(received.count)assert(received.rf==100000000ll*(1ll<<20));if(refresh_before){assert(runtime.progress({3'000'030'000}));assert(backend->pending()==1&&backend->begins()==1);runtime::FieldOutcome cancelled;cancelled.id=RFReferenceFrequency::id;cancelled.status=runtime::FieldStatus::cancelled;(void)backend->complete_next(cancelled);}return;}assert(backend->pending()==1);assert(received.count==before);assert(device->timeline().ordinal()==(future?110:late_start?256:0));auto completed=backend->complete_next();assert(completed&&*completed);auto result=runtime.progress({hold+500'000});if(!result)std::fprintf(stderr,"future%d mtu%zu late%d jump%d completion_error%u retry%d\n",future,mtu,late_start,jump_from_below,unsigned(result.error().code),result.error().retryable);assert(result||result.error().retryable);assert(runtime.progress({hold+600'000}));assert(received.count>before&&received.rf==100025000ll*(1ll<<20));const auto resumed=received.count;for(std::uint64_t dt=700'000;dt<=10'700'000;dt+=100'000)assert(runtime.progress({hold+dt}));assert(received.count>resumed&&received.rf==100025000ll*(1ll<<20));assert(runtime.run_for(10'000'000));
}
int main(int argc,char**argv){const int selected=argc==2?argv[1][0]-'0':-1;for(int i=0;i<6;++i)if(selected<0||selected==i){switch(i){case 0:trial(false);break;case 1:trial(true);break;case 2:trial(false,1500);break;case 3:trial(false,1500,true);break;case 4:trial(true,100,false,true);break;case 5:trial(true,100,false,false,true);break;}}}
