#include "../../../examples/frequency_scan/endpoint_options.hpp"
#include <cassert>
using namespace vita::examples::frequency_scan;
static auto parse(EndpointRole role,std::initializer_list<std::string_view> values){return parse_endpoint_options(role,std::span<const std::string_view>{values.begin(),values.size()});}
int main(){auto controller=parse(EndpointRole::controller,{}),device=parse(EndpointRole::controllee,{});assert(controller&&device);assert(controller->local.data==41000&&controller->local.cancellation==41002&&controller->peer.data==42000);assert(device->local.data==42000&&device->peer.data==41000);assert(controller->address=="127.0.0.1"&&controller->isolated_lab&&controller->simulated_pps);assert(!parse(static_cast<EndpointRole>(99),{}));
 for(auto text:{"0","65534","65535","65536","18446744073709551616","-1","+1","1.0","1e3",""," 123"})assert(!parse(EndpointRole::controller,{"--local-base-port",text}));
 for(auto base:{"41998","41999","42000","42001","42002"})assert(!parse(EndpointRole::controller,{"--local-base-port",base}));
 assert(parse(EndpointRole::controller,{"--local-base-port","41997"}));assert(parse(EndpointRole::controller,{"--local-base-port","42003"}));auto upper=parse(EndpointRole::controller,{"--local-base-port","65533"});assert(upper&&upper->local.cancellation==65535);assert(!parse(EndpointRole::controller,{"--peer-base-port"}));assert(!parse(EndpointRole::controller,{"--local-base-port","1","--local-base-port","2"}));assert(!parse(EndpointRole::controller,{"--peer-base-port","2","--local-base-port","1"}));assert(!parse(EndpointRole::controller,{"--address","8.8.8.8"}));assert(!parse(EndpointRole::controller,{"--continuous","--sweeps","2"}));assert(!parse(EndpointRole::controller,{"--sweeps","2","--continuous"}));assert(!parse(EndpointRole::controller,{"--dwell-ms","0"}));auto rate=parse(EndpointRole::controllee,{"--sample-rate-hz","123456","--local-base-port","1","--peer-base-port","4"});assert(rate&&rate->scan.scene.sample_rate==123456);
}
