#include "../../../examples/frequency_scan/application.hpp"
#include <vita/profiles/iq/lab.hpp>
#include <cassert>
using namespace vita;namespace demo=vita::examples::frequency_scan;namespace tr=vita::runtime::transport;
using Adapter=adapters::loopback::Loopback<32,128,128>;
static tr::Capabilities caps(){tr::Capabilities c;c.reserved_control_slots=8;c.reserved_cancellation_slots=2;return c;}
static tr::TransportFactory factory(){return {nullptr,Adapter::metadata_bytes()+128,32,caps(),[](void*,tr::HostBindings h)noexcept->Result<tr::TransportBinding>{auto owner=std::make_shared<Adapter>(h.rx_data,h.rx_control,h.rx_cancellation,h.admission,h.routes,h.counters,caps());return tr::TransportBinding{owner,owner.get(),Adapter::metadata_bytes()+128,32,caps(),
 [](void*p,tr::TxSubmission&& value)noexcept->std::expected<tr::TxToken,tr::RejectedSubmission>{auto frame=tr::inspect(value.storage);assert(frame);const auto& e=frame->envelope;if(e.ack&&e.command&&((e.command->cam>>23)&3)==2&&!(e.command->cam&(1u<<20)))value.fault.lose=true;return static_cast<Adapter*>(p)->try_send(std::move(value));},
 [](void*p)noexcept->Result<bool>{return static_cast<Adapter*>(p)->progress_next();},[](void*p,tr::TxToken t)noexcept{return static_cast<Adapter*>(p)->outstanding(t);},[](void*p)noexcept{static_cast<Adapter*>(p)->close();},[](void*p,tr::TxToken t)noexcept->Result<void>{return static_cast<Adapter*>(p)->prove_quiescent(t);},[](void*,std::span<const tr::Association>,bool)noexcept->Result<void>{return {};},[](void*p)noexcept{static_cast<Adapter*>(p)->close();}};}};}
int main(){auto config=profiles::iq::lab::config(0xabcdef);auto pools=profiles::iq::lab::pools();assert(config&&pools);config->transport=factory();auto made=demo::Runtime::create(*config,std::move(*pools));assert(made);auto tuner=std::make_shared<demo::VirtualTuner>();runtime::transaction::VirtualRule rule;rule.supported=false;assert(tuner->model.set_rule(RFReferenceFrequency::id,rule));StreamConfig s;s.sid=1;s.controller_id=2;s.controllee_id=3;s.sample_rate=100000;s.profile=profiles::iq::Profile::frequency_tunable;s.device=demo::VirtualTuner::binding(tuner);auto device=(*made)->add_controllee(s);assert(device);auto controller=(*made)->add_controller(*device);assert(controller);assert((*made)->observe_pps({0},{1000,0})&&device->start());auto options=demo::parse_options({});assert(options);auto policy=profiles::iq::SweepPolicy::create(options->sweep);assert(policy);demo::ScanApplication application(*controller,*policy,*options);assert(application.begin());bool failed=false;std::uint64_t when=0;for(;when<20'000'000;when+=100000){auto progressed=(*made)->progress({when});assert(progressed||progressed.error().retryable);auto result=application.progress({when});if(!result){failed=true;break;}}assert(failed&&when<options->sweep.timeout_ns&&application.confirmed()==0&&tuner->model.begins()==0&&tuner->model.writes()==0);made->reset();}
