#include <vita/profiles/iq/lab.hpp>
#include <vita/profiles/iq/frequency_scan.hpp>
#include <vita/runtime/public/runtime.hpp>
#include <cassert>
#include <cstdio>
using namespace vita;
using Backend=runtime::transaction::VirtualBackend<4>;
static void progress(auto& r,std::uint64_t now){for(unsigned n=0;n<6;++n){auto p=r.progress({now});if(!p)std::fprintf(stderr,"progress%llu round%u error%u retry%d\n",(unsigned long long)now,n,unsigned(p.error().code),p.error().retryable);assert(p||p.error().retryable);}}
struct Received{unsigned recovered=0,loss=0;static void data(void*p,const runtime::context::BorrowedSignalRx& rx)noexcept{auto& r=*static_cast<Received*>(p);if(std::get<std::uint32_t>(rx.metadata.state.fields[0].value)!=4)return;assert(rx.metadata.confidence==runtime::context::Confidence::known);assert(std::get<Hertz>(rx.metadata.state.fields[4].value)==*Hertz::from_integer(100000000));++r.recovered;if(rx.metadata.events&runtime::context::sample_loss_indicator)++r.loss;}};
struct RealScene {
 profiles::iq::VirtualRfScene scene=*profiles::iq::VirtualRfScene::create();bool reset_waiting=false,recovered=false;std::uint64_t origin=0;unsigned produced=0;
 static Result<void> effect(void*p,const runtime::EffectiveEvent& e)noexcept{auto& s=*static_cast<RealScene*>(p);auto result=s.scene.effective(e);if(result&&s.reset_waiting){assert(e.sample_ordinal>0&&s.scene.phase_numerator()==0);s.origin=e.sample_ordinal;s.recovered=true;s.reset_waiting=false;}return result;}
 static Result<void> produce(void*p,profiles::iq::SampleWriteWindow& w)noexcept{auto& s=*static_cast<RealScene*>(p);auto result=s.scene.produce(w);if(result&&s.recovered){assert(s.scene.phase_numerator()==((w.first_ordinal()+w.count()-s.origin)%2)*50000);++s.produced;}return result;}
};
struct Reinitialize {Backend* backend;RealScene* source;static Result<bool> run(void*p,const runtime::StateSnapshot&)noexcept{auto& self=*static_cast<Reinitialize*>(p);auto reset=self.backend->reinitialize();if(!reset)return std::unexpected(reset.error());if(self.source){auto fresh=profiles::iq::VirtualRfScene::create_for_recovery();if(!fresh)return std::unexpected(fresh.error());self.source->scene=*fresh;self.source->reset_waiting=true;}return true;}};
static void trial(bool actual_scene){auto config=profiles::iq::lab::config(0xabcdef);auto pools=profiles::iq::lab::pools();assert(config&&pools);auto made=VitaRuntime<1,4,32,65536>::create(*config,std::move(*pools));assert(made);auto& r=**made;auto backend=std::make_shared<Backend>();Received received;RealScene scene;StreamConfig stream;if(actual_scene)stream.source={&scene,RealScene::produce,RealScene::effect};stream.receiver={&received,Received::data,nullptr};stream.sid=1;stream.controller_id=2;stream.controllee_id=3;stream.sample_rate=100000;stream.ip_mtu=100;stream.profile=profiles::iq::Profile::frequency_tunable;stream.device={backend->binding(),backend,sizeof(Backend),nullptr};auto d=r.add_controllee(stream);assert(d);auto c=r.add_controller(*d);assert(c);assert(r.observe_pps({0},{1000,0})&&d->start());progress(r,0);auto confirmed=d->confirmed_state();
 CommandOptions scheduled;scheduled.timing_mode=1;scheduled.execute_at=runtime::timing::ProtocolTime{1000,2'200'000'000};auto before=c->set_center_frequency(*Hertz::from_integer(100025000),scheduled);assert(before);progress(r,0);assert(c->cancel(*before,QuerySelection{QueryField::center_frequency}));progress(r,0);auto cancelled=c->wait(*before,0,WaitEvidence::cancellation_execution);assert(cancelled&&cancelled->observation.confirms_cancellation&&!cancelled->observation.confirms_execution);assert(backend->begins()==0&&backend->writes()==0);assert(d->confirmed_state().fields[4].value==confirmed.fields[4].value);
 auto running=c->set_center_frequency(*Hertz::from_integer(100050000));assert(running);progress(r,110000);assert(backend->pending()==1);auto capability=backend->pending_capability();assert(capability);assert(c->cancel(*running,QuerySelection{QueryField::center_frequency}));progress(r,110000);auto stopped=c->wait(*running,0,WaitEvidence::cancellation_execution);assert(stopped&&stopped->observation.confirms_cancellation);assert(backend->pending()==0);runtime::FieldOutcome contradiction;contradiction.id=RFReferenceFrequency::id;contradiction.status=runtime::FieldStatus::executed;contradiction.value=*Hertz::from_integer(100050000);contradiction.validity=runtime::Validity::known;assert(!capability->complete(contradiction));progress(r,220000);assert(d->confirmed_state().fields[4].validity==runtime::Validity::unknown);assert(d->status()!=SourceStatus::running);const auto packets=d->metrics().packets;progress(r,330000);assert(d->metrics().packets==packets);
 RecoveryConfig recovery;recovery.new_sid=4;recovery.peer_ready=true;recovery.confirmed_state=d->confirmed_state();recovery.confirmed_state.fields[0].value=std::uint32_t{4};assert(!d->recover(recovery));capability.reset();recovery.confirmed_state=confirmed;recovery.confirmed_state.fields[0].value=std::uint32_t{4};Reinitialize initializer{backend.get(),actual_scene?&scene:nullptr};recovery.reinitialize_context=&initializer;recovery.reinitialize=Reinitialize::run;assert(d->recover(recovery));for(unsigned i=0;i<16&&d->sid()!=4;++i)progress(r,440000+i*110000);assert(d->sid()==4);assert(d->confirmed_state().fields[4].validity==runtime::Validity::known&&d->confirmed_state().fields[4].value==confirmed.fields[4].value);assert(r.run_for(1'000'000));assert(received.recovered>=2&&received.loss==1);assert((std::get<std::uint32_t>(d->confirmed_state().fields[2].value)&runtime::context::sample_loss_indicator)==0);if(actual_scene)assert(scene.recovered&&scene.origin>0&&scene.produced>=2&&!scene.scene.faulted());
}

int main(){trial(false);trial(true);}
