#include <vita/runtime/transaction/outcomes.hpp>
#include <cassert>
using namespace vita;using namespace vita::codec;using namespace vita::runtime::transaction;
static Observation deliver(ControllerObserver& observer,bool scheduled,bool partial=false,std::uint32_t errors=0,bool timing=false,bool warning=false){AckRecord ack;ack.request.type=PacketType::command;ack.request.stream_id=1;ack.request.class_id=ClassId{0xabcdef,2,0x120};ack.request.command=Command{0xa91f0000u|(timing?0x1000u:0),7,Identifier::short_id(2),Identifier::short_id(3)};if(timing)ack.request.timestamp={Tsi::gps,Tsf::picoseconds,1000,0};auto cam=Cam::parse(ack.request,Profile::iq_frequency_tunable);assert(cam);ack.cam=*cam;ack.kind=AckKind::validation;ack.scheduled_or_executed=scheduled;ack.partial=partial;ack.diagnostics[4].errors=errors;ack.diagnostics[4].warnings=warning?precision:0;ack.timing=timing?7:0;std::array<std::byte,256> wire{};auto size=encode_response(ack,wire);assert(size);auto view=decode_packet(Bytes{wire}.first(*size),DecodeOptions{RequestContext{cam->raw}});assert(view);assert(observer.receive(*view));return observer.observation();}
int main(){for(unsigned test=0;test<6;++test){ControllerObserver observer(7);auto value=deliver(observer,test!=1,test==2,test==3?unsupported:test==4?state_indeterminate:0,test==5);assert(value.validation_outcome_known&&value.validation_accepted==(test==0));assert(!value.success&&!value.confirms_execution&&value.response_kind==ObservationKind::validation);}ControllerObserver warning(7);assert(deliver(warning,true,false,0,false,true).validation_accepted);
 ControllerObserver late(7);late.timeout();auto timeout=late.timeout_observation();assert(timeout);auto accepted=deliver(late,true);assert(accepted.kind==ObservationKind::late_response&&accepted.validation_outcome_known&&accepted.validation_accepted&&!accepted.success&&!accepted.confirms_execution&&late.timeout_observation()==timeout);
 ControllerObserver rejected(7);rejected.timeout();auto denied=deliver(rejected,false,false,unsupported);assert(denied.validation_outcome_known&&!denied.validation_accepted&&!denied.success);
 ControllerObserver contradictory(7);assert(deliver(contradictory,true).validation_accepted);auto conflict=deliver(contradictory,false);assert(conflict.contradictory&&!conflict.validation_outcome_known&&!conflict.validation_accepted&&!conflict.success&&!conflict.confirms_execution);
}
