foreach(example controller controllee combined)
  add_executable(vita_${example}_example ${example}.cpp)
  target_link_libraries(vita_${example}_example PRIVATE vita::core)
  if(CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU")
    target_compile_options(vita_${example}_example PRIVATE -fno-exceptions -fno-rtti)
  endif()
  if(BUILD_TESTING)
    add_test(NAME p10_example_${example} COMMAND vita_${example}_example)
    set_tests_properties(p10_example_${example} PROPERTIES LABELS "integration;examples")
  endif()
endforeach()

if(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/frequency_scan/CMakeLists.txt")
  add_subdirectory(frequency_scan)
endif()
