#include "../P10/runtime_fixture.hpp"
#include <vector>
using namespace vita;using namespace vita::runtime;using namespace verify_p10;
static std::vector<memory::BufferLease> exhaust(memory::ExternalPool& pool,std::size_t bytes){std::vector<memory::BufferLease> held;for(;;){auto lease=pool.acquire({bytes});if(!lease)break;held.push_back(std::move(*lease));}return held;}
struct Seen{unsigned packets=0;static void receive(void*p,const context::BorrowedSignalRx& signal)noexcept{if(signal.metadata.confidence!=context::Confidence::known)std::abort();++static_cast<Seen*>(p)->packets;}};
using Runtime=VitaRuntime<1,4,32,65536>;
int main(){
 {auto pools=external_pools();auto made=Runtime::create(runtime_config(),pools);if(!made)return 1;Seen seen;auto config=stream_config();config.receiver={&seen,Seen::receive,nullptr};auto device=(*made)->add_controllee(config);if(!device||!(*made)->observe_pps({0},{1000,0})||!device->start())return 2;auto held=exhaust(pools.control,2048);(*made)->progress({0});if(held.empty()||device->status()!=SourceStatus::running||seen.packets)return 3;if(((*made)->progress({1000000}),false)||device->status()!=SourceStatus::running)return 4;held.clear();if(!(*made)->progress({2000000})||device->status()!=SourceStatus::running||!seen.packets)return 5;}
 {auto pools=external_pools();auto made=Runtime::create(runtime_config(),pools);if(!made)return 6;auto device=(*made)->add_controllee(stream_config());if(!device||!(*made)->observe_pps({0},{1000,0})||!device->start())return 7;auto held=exhaust(pools.control,2048);if(((*made)->progress({0}),false)||((*made)->progress({9999999}),false)||device->status()!=SourceStatus::running)return 8;if(((*made)->progress({10000000}),false)||device->status()!=SourceStatus::context_unavailable)return 9;held.clear();if(!(*made)->progress({10000001})||device->status()!=SourceStatus::context_unavailable)return 10;}
 {auto pools=external_pools();auto made=Runtime::create(runtime_config(),pools);if(!made)return 11;Seen seen;auto config=stream_config();config.receiver={&seen,Seen::receive,nullptr};auto device=(*made)->add_controllee(config);if(!device||!(*made)->observe_pps({0},{1000,0})||!device->start()||!(*made)->progress({0}))return 12;const auto before=seen.packets;auto held=exhaust(pools.header,28);if(((*made)->progress({256000}),false)||device->status()!=SourceStatus::running||seen.packets!=before)return 13;held.clear();if(!(*made)->progress({512000})||device->status()!=SourceStatus::running||seen.packets<=before)return 14;}
 {auto pools=external_pools();pools.header=external_pool(64,128);pools.payload=external_pool(2048,128);auto made=Runtime::create(runtime_config(),pools);if(!made)return 15;auto config=stream_config();config.sample_rate=100000000;auto device=(*made)->add_controllee(config);if(!device||!(*made)->observe_pps({0},{1000,0})||!device->start())return 16;auto held=exhaust(pools.control,2048);for(unsigned n=0;n<64;++n)if(((*made)->progress({n*2560ull}),false)||device->status()!=SourceStatus::running)return 17;(*made)->progress({64*2560ull});if(device->status()!=SourceStatus::running||device->metrics().samples!=64*256)return 18;(*made)->progress({10000000});if(device->status()!=SourceStatus::context_unavailable)return 21;}

 {auto made=Runtime::create(runtime_config(),external_pools());if(!made)return 19;auto config=stream_config();config.source={nullptr,[](void*,profiles::iq::SampleWriteWindow&)noexcept->Result<void>{return std::unexpected(Error{ErrorCode::capacity_exhausted});}};auto device=(*made)->add_controllee(config);if(!device||!(*made)->observe_pps({0},{1000,0})||!device->start()||((*made)->progress({0}),false)||device->status()!=SourceStatus::faulted)return 20;}
 return 0;
}
